version: '2'

services:
  mysql:
    image: mariadb:10
    container_name: "memory-mysql"
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=memory
      - MYSQL_DATABASE=memory
      - MYSQL_USER=memory

  app:
    image: php:7-fpm-alpine
    container_name: "memory-php"
    restart: on-failure
    links:
      - mysql
    volumes:
      - ./src/:/var/www/html/
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_PASSWORD=memory
      - MYSQL_DATABASE=memory
      - MYSQL_USER=memory
      - MYSQL_HOST=mysql:3306

  web:
    image: nginx:1-alpine
    container_name: "memory-nginx"
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "memory-phpmyadmin"
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      PMA_ABSOLUTE_URI: http://localhost:8080
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: memory

  mail:
    image: mailhog/mailhog
    container_name: "memory-mail"
    user: root
    ports:
      - 1080:1080
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:1080
      MH_UI_BIND_ADDR: 0.0.0.0:1080

volumes:
  mysql: